#!/usr/bin/env python

# pip deps
# rdflib

import argparse

from belfastdata.harvest import HarvestRelated

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Harvest related RDF from VIAF, DBpedia, and GeoNames'
    )
    parser.add_argument('files', metavar='FILE', nargs='+',
                        help='files to be processed')
    parser.add_argument('-o', '--output', metavar='DIR',
                        help='base directory for harvested content',
                        required=True)
    parser.add_argument('-f', '--format', metavar='FORMAT', default='xml',
                        help='output format (one of: %(choices)s; default is %(default)s)',
                        choices=['xml', 'n3', 'turtle'])
    args = parser.parse_args()
    HarvestRelated(args.files, args.output, format=args.format)
