#!/usr/bin/env python

import argparse

from belfastdata.clean import SmushGroupSheets

# NOTE: this one probably doesn't need to be a separate script
# now that it is part of the combined script
# (unlikely to be run separately or useful to anyone else)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='De-dupe Belfast Group sheets by smushing URIs'
    )
    parser.add_argument('files', metavar='FILE', nargs='+',
                        help='files to be processed')
    args = parser.parse_args()
    SmushGroupSheets(args.files)
